import dayjs from 'dayjs/esm';

import { IMerchandise, NewMerchandise } from './merchandise.model';

export const sampleWithRequiredData: IMerchandise = {
  id: 96748,
};

export const sampleWithPartialData: IMerchandise = {
  id: 65860,
  name: 'synergy',
  nature: 'Account',
  group_vthh: 'JBOD Seychelles',
  describe: 'EXE',
  explain_buy: 'Michigan Card',
  explain_sell: 'invoice Peso actuating',
  main_dvt: 'Outdoors Industrial PCI',
  quantity_inventory: 26534,
  implicitly_repository: 'array deploy Car',
  warehouse_account: 'Facilitator',
  expense_account: 'bricks-and-clicks',
  income_account: 'Data website',
  sale_account: 'Infrastructure parallelism',
  rate_ckmh: 19543,
  fixed_purchase_price: 51291,
  unit_price_sell_3: 87669,
  fixed_unit_price: 18844,
  unit_price_after_tax: 25034,
  tax_rate_xk: 13777,
  group_hhdv_taxable_ttdb: 'FTP Central TCP',
  unfollow: 33982,
  inventory_number: 7123,
  follow: 24874,
  percent_discount: 28124,
  calculation: 'cross-platform 24/365 Rubber',
  describe1: 'Architect HDD',
  unit_price_1: 51972,
  unit_price_2: 89632,
  material_name: 'bandwidth-monitored',
  amount: 'Keyboard',
  specification_code: 'Qatari',
  display_name: 'Dynamic Mozambique',
  allow_same: 'relationships',
  created_date: dayjs('2022-12-15'),
};

export const sampleWithFullData: IMerchandise = {
  id: 85616,
  code: 'calculate Kids',
  name: 'wireless',
  nature: 'transmit Ball Forward',
  group_vthh: 'Rubber groupware Plaza',
  describe: 'Principal Frozen index',
  explain_buy: 'multi-state',
  explain_sell: 'Indiana Refined',
  main_dvt: 'Station invoice black',
  warranty_period: 'Open-source Ohio',
  quantity_inventory: 51867,
  source: 'Overpass Home',
  implicitly_repository: 'Intelligent',
  warehouse_account: 'paradigms Interactions Oregon',
  expense_account: 'Namibia end-to-end',
  income_account: 'Games',
  discount_account: 'Ohio SQL override',
  sale_account: 'Tactics',
  return_account: 'sensor Licensed',
  rate_ckmh: 41205,
  fixed_purchase_price: 47838,
  latest_purchase_price: 56897,
  unit_price_sell_1: 27037,
  unit_price_sell_2: 74737,
  unit_price_sell_3: 81649,
  fixed_unit_price: 68527,
  unit_price_after_tax: 51101,
  tax_rate_gtgt: 'card SSL',
  tax_rate_nk: 51424,
  tax_rate_xk: 56608,
  group_hhdv_taxable_ttdb: 'Practical intranet',
  unfollow: 90865,
  inventory_number: 41679,
  characteristic: 'Organized bluetooth Beauty',
  inventory_value: 58240,
  follow: 47701,
  discount: 47569,
  from_amount: 'Cross-platform',
  to_amount: 'cutting-edge visualize',
  percent_discount: 52398,
  discount_amount: 53969,
  conversion_unit: 'XML blue Guinea',
  primary_unit_conversion_rate: 95125,
  calculation: 'Pants cohesive AGP',
  describe1: 'clear-thinking Borders',
  unit_price_1: 49671,
  unit_price_2: 13046,
  unit_price_3: 13925,
  fixed_unit_price1: 78485,
  material_code: 'Intelligent Personal',
  material_name: 'strategize SDD Global',
  dvt: 'Group',
  amount: 'Home',
  specification_code: 'sexy line',
  display_name: 'Mouse Small compress',
  allow_same: 'Future-proofed methodologies',
  created_date: dayjs('2022-12-15'),
  keyUUID: 'Music grey auxiliary',
};

export const sampleWithNewData: NewMerchandise = {
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
